# Generated by Django 2.2.12 on 2024-12-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20241228_2227'),
        ('student', '0004_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(related_name='students', through='quiz.TakenQuiz', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ville',
            field=models.CharField(default='Abobo', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/students/'),
        ),
        migrations.DeleteModel(
            name='StudentReponse',
        ),
    ]
