# Generated by Django 2.2.12 on 2024-12-28 21:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_cours_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200420_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct answer')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='date',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typequestion',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='temps',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='titre',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=200000, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='classe',
            field=models.ForeignKey(default=20000, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='school.Classe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(default=520000, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='school.Cours'),
        ),
        migrations.DeleteModel(
            name='Devoir',
        ),
    ]
